# numpy套件

In [4]:
alist=[1,2,3,4]
print(alist*3)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [5]:
#numpy套件 ndarry型態 提供element-wise的操作
import numpy as np
andarray=np.array([1,2,3,4,5])
print(andarray*3)

[ 3  6  9 12 15]


In [6]:
print(type(andarray))
print(andarray.ndim)
print(andarray.shape)
print(andarray.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


In [7]:
z=np.zeros(7)
print(z)#7個元素都為0id ndarray
print(np.zeros((2,7)))#12個元素都為0的2d ndarray
print(np.empty((2,7,2)))#24個元素都為初始化的值
print(np.arange(10))#10個元素為0-9的id ndarray

[0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[[1.14904711e-311 9.23902758e-322]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 5.02034658e+175]
  [9.42822258e-047 2.34453107e-056]
  [1.88560240e+185 9.60465760e-071]
  [5.01163192e+217 5.49419094e-143]
  [1.50008929e+248 1.06396443e+224]]

 [[1.47765135e+248 4.30625279e-096]
  [9.08366793e+223 1.58865811e-076]
  [2.37859500e+184 1.05097136e-046]
  [4.88944640e-033 2.24729310e+174]
  [1.56605686e-076 1.17527017e-047]
  [6.37456093e-062 3.12226345e-033]
  [1.28625693e+248 4.24948967e-086]]]
[0 1 2 3 4 5 6 7 8 9]


# ndarray進階

In [8]:
myarray=np.arange(10)
print(myarray)
print(myarray[0])
print(myarray[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [9]:
#2維ndarray取值
my2darray = np.array([np.arange(0,5),np.arange(5,10)])
print(my2darray)
print(my2darray[1,:])#第二列資料
print(my2darray[:,1])#第二欄資料
print(my2darray[1,1])#第二列第二欄資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [10]:
#假設有六組"Modern web","DevOps","Cloud","big data","security","自我挑戰"
#期參加人數分別[56,8,19,14,6,71]
groups=["Modern web","DevOps","Cloud","big data","security","自我挑戰"]
ironman=[56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern web' 'DevOps' 'Cloud' 'big data' 'security' '自我挑戰']
[56  8 19 14  6 71]


In [11]:
#用人數去篩選
print(ironman_array >= 10)
print(groups_array[ironman_array>=10])
print(groups_array !="自我挑戰")
print(ironman_array[groups_array !="自我挑戰"])

[ True False  True  True False  True]
['Modern web' 'Cloud' 'big data' '自我挑戰']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray轉智

In [12]:
my1darray=np.arange(10)
print(my1darray)
my2darray=my1darray.reshape((2,5))
print(my2darray)
print(my2darray.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [13]:
print(np.arange(24).reshape(4,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [14]:
#ndarray nan(空值)
nanarray=np.array([56,8,19,14,6,np.nan])
print(nanarray)

[56.  8. 19. 14.  6. nan]
